### ISSUE TITLE
Failing test A-Z

### ISSUE THREAD

**Issue by matthewdking** [fac-13/ab-fac-todo#23]
Awesome to see some great tests. Before merging to master you should run your tests to ensure you haven't broken any tests.

**Comment by vlbee** [comment]
Fixed!  Could not figure out though why 2 lines below were not running. 

![image](https://user-images.githubusercontent.com/32312712/37204620-6a76c248-2389-11e8-84cf-22d7d279cd68.png)

**Comment by matthewdking** [comment]
@vlbee as far as I am aware the following lines aren't testable
```js
if (typeof module !== 'undefined') {
  module.exports = todoFunctions;
}
```
However if you add `/* istanbul ignore next */`to the line before it will ignore the next section of code, increasing your test coverage. This is why code coverage should always be taken with a pinch of salt as it can be altered to increase without actually testing. For reference check out this [link from the docs](https://github.com/gotwarlost/istanbul/blob/master/ignoring-code-for-coverage.md).
