### ISSUE TITLE
Simplify markTodo function

### ISSUE THREAD

**Issue by matthewdking** [fac-13/ab-fac-todo#24]
The following code can be simplified slightly
```js
      if(value.id === idToMark) {
        if(value.done === false) {
          value.done = true;
        } else if(value.done === true) {
          value.done = false;
        }
      }
```
to...

```js
if (value.id === idToMark) {
  value.done = !value.done
}
```
This will create a toggle that will change the markTodo to the opposite of its current value. It is slightly more readable than having a nested if statement.

**Comment by nik0lz** [comment]
Ingenious! Thank you.
