### ISSUE TITLE
🎉🎉🎉Well done!!🎉🎉🎉

### ISSUE THREAD

**Issue by jamiecoe** [fac-13/ab-fac-todo#25]
Hi ab-fac people,

Well done, this is awesome work!! 
- Everything seems to work well, no bugs 🐛
- Clear, simple and intuitive design
- (almost) All tests passing 😉
- Mobile responsive 📱 
- All functionality (including sort stretch goal 🏆)

**Comment by vlbee** [comment]
tests updated to all pass with decent code coverage - i think!  :)
