### ISSUE TITLE
A few git flow things

### ISSUE THREAD

**Issue by matthewdking** [fac-13/ab-fac-todo#32]
Overall git flow is looking really good :tada: 

A few things that could improve your git flow further.
- Add a description to your PRs, this means anyone can quickly tell from your description what work you completed in the PR. You should link to an issue here as well. 
- Branches, you have lots of these which is a good thing. Just make sure when you merge :twisted_rightwards_arrows: you also delete the branch :deciduous_tree:  The only branches that should be open are master and any unmerged code.
- Commits are all descriptive :+1: just make sure to reference an issue here as well with #issueNum

**Comment by vlbee** [comment]
will delete branches
