### ISSUE TITLE
nitpick: function consistency

### ISSUE THREAD

**Issue by tspeed90** [fac-13/ab-fac-todo#33]
Your logic file looks great, I don't really see anything to complain about, so I'll nitpick.
In all of your functions you do the object cloning at the top of the function, except in deleteToDo. For the sake of consistency, maybe consider moving the cloning to the top so all functions start out with the same process. 

https://github.com/fac-13/ab-fac-todo/blob/master/logic.js#L26-L36

**Comment by nik0lz** [comment]
Point noted! Ta!
