### ISSUE TITLE
Consider chaining functions for readability

### ISSUE THREAD

**Issue by jamiecoe** [fac-13/ab-fac-todo#34]
I don't know if you guys have come across chaining functions before? It can make things look a bit neater and readable. 

Take this:

```
var cloneTodos = todoFunctions.cloneArrayOfObjects(todos);
    var nonIdMatch = cloneTodos.filter(function(todoObj) {
      if (todoObj.id !== idToDelete) {
        return todoObj;
      }
    });
    return nonIdMatch;
```

And change it to this:
```
return todoFunctions.cloneArrayOfObjects(todos).filter(function(todoObj) {
      return todoObj.id !== idToDelete;
    });
```

Then for me (as a new programmer coming to your project), I don't have to keep track of variable names like `cloneTodos` and `nonIdMatch`. I can just follow the chain of functions which have names clearly saying what they do, so I can understand quickly what's going on.

**Comment by nik0lz** [comment]
Function updated on "fix login.js  issues" branch - forgot to link it to this issue number.
